apiVersion: kubeai.org/v1
kind: Model
metadata:
    name: chandra-ocr-2
spec:
    autoscalingDisabled: true
    replicas: 1
    features: [TextGeneration]
    url: s3://projet-models-hf/diffusion/hf_hub/datalab-to/chandra-ocr-2
    engine: VLLM
    image: vllm/vllm-openai:v0.27.1
    args:
        - --dtype=bfloat16
        - --limit-mm-per-prompt.video=0
        - --limit-mm-per-prompt.image=1
        - --gpu-memory-utilization=0.90
        - --tensor-parallel-size=1
        - --max-model-len=65536
        - --max-num-seqs=32
        - --async-scheduling
        - '--override-generation-config={"temperature": 0.0, "top_p": 0.1}'
    resourceProfile: vram-80gb:1
    env:
        AWS_ENDPOINT_URL: https://minio.lab.sspcloud.fr
