apiVersion: kubeai.org/v1
kind: Model
metadata:
    name: diffusiongemma-26b-moe
spec:
    autoscalingDisabled: true
    replicas: 0
    features: [TextGeneration, SpeechToText]
    url: s3://projet-models-hf/diffusion/hf_hub/google/diffusiongemma-26B-A4B-it
    engine: VLLM
    image: vllm/vllm-openai:gemma
    args:
        - --max-num-seqs=4
        - --tool-call-parser=gemma4
        - --tensor-parallel-size=1
        - --enable-auto-tool-choice
        - --chat-template=examples/tool_chat_template_gemma4.jinja
        - --reasoning-parser=gemma4
        - --kv-cache-dtype=fp8
        - --max-model-len=131072
        - --attention-backend=TRITON_ATTN
        - --generation-config=vllm

    resourceProfile: vram-94gb:1
    env:
        AWS_ENDPOINT_URL: https://minio.lab.sspcloud.fr
