apiVersion: kubeai.org/v1
kind: Model
metadata:
    name: qwen3-8-27b
spec:
    autoscalingDisabled: true
    replicas: 1
    features: [TextGeneration]
    url: s3://projet-models-hf/diffusion/hf_hub/Qwen/Qwen3.8-27B-FP8
    engine: VLLM
    image: vllm/vllm-openai:v0.27.1
    args:
        - --reasoning-parser=qwen3
        - --max-model-len=131072
        - --tensor-parallel-size=1
        - --enable-auto-tool-choice
        - --tool-call-parser=qwen3_coder
        - --mm-encoder-tp-mode=data
    resourceProfile: vram-94gb:1
    env:
        AWS_ENDPOINT_URL: https://minio.lab.sspcloud.fr
